mybatis:
  type-aliases-package: share.king.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    interceptors:

logging:
  level:
    share.king: debug
spring:
  profiles:
    active: test
  mail:
    host: smtp.163.com
    port: 25
    username: 13218020018@163.com
    password: zhh19961026
    from: 13218020018@163.com
server:
  port: 11111
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql