mybatis:
  type-aliases-package: share.king.entity
  mapper-locations: [classpath:mybatis/mapper/*.xml,classpath:mybatis/mapper/ext/*.xml]
  configuration:
    map-underscore-to-camel-case: true
    interceptors:

logging:
  level:
    share.king: debug
spring:
  profiles:
    active: test
  mail:
    host: smtp.163.com
    port: 25
    username:
    password:
    from:
server:
  port: 11111
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql